### ISSUE TITLE
Remove arbitrary (?) beacon count limitation

### ISSUE THREAD

**Issue by dermotduffy** [turbo-lab/android-beacon-mqtt#29]
It does not seem possible to add more than 4 beacons -- why does this limitation exist?

Use case: I am trying to use beacons for room presence detection (reporting to home assistant which room the android device is in, via mqtt). This beacon count limitation limits the effectiveness to 4 rooms only. 

If there is a need for such a limitation, bumping it up substantially would also be workable (e.g. 10 / 20 / 50 / 100).

Thanks for considering.

**Comment by turbulator** [comment]
Hi,
I'm thinking of Pro version of app. Unlimited count of beacons would be the killer feature for that.

**Comment by dermotduffy** [comment]
Ah, I see. Do you have a timeline in mind for making that available? 

If it's not going to be soon, then I suppose the options are that you consider removing the limit for now (until the pro version is available for people to purchase), or I guess I'll need to find an alternative as a 4-beacon limit will not work for my usecase. There are alternatives (e.g. find3, or tasker-based), but this app is the most convenient I have found so far.

Related: I think TLS support is a must-have for either pro or basic versions, but I could also see multiserver being a pro feature.

**Comment by turbulator** [comment]
I have no fixed date because I don't know how I can get legal money from Google in my country. It is too complex. 

I should be honest with my users: I can't remove the limit now and return it in the future. It is wrong way.

I agree - 4 beacons is very strict limitation. We should find the acceptable level of compromise. I think 10 beacons is much better. You can process significant more scenes. And there will be the opportunity for a professional version.  What do you think abouth that?

**Comment by dermotduffy** [comment]
That sounds like a good compromise to me, thank you!

**Comment by turbulator** [comment]
I've a personal ask for you: per room presense detection is very interesting topic for me too. Please share your experience (positive or negative) in my topic on HA website: https://community.home-assistant.io/t/beacon-mqtt-android/108127/33 when you will be ready.

**Comment by turbulator** [comment]
The limitation will be increased in v0.3

**Comment by dermotduffy** [comment]
Happy to share my thoughts/setup once I get everything going smoothly!

I saw an update yesterday and it appears to be labeled v0.3 -- but I can't seem to add beyond the 4th beacon. Has the limitation been removed yet, or perhaps I'm doing something wrong?

**Comment by turbulator** [comment]
Great! Don't hesitate to open new issues regarding Master's beacon functionality. Will glad to help you and make your usecase really workable.

That update was made on Friday, I think, and was connected with an optimisation of app's size. Have a look on release notes in Google Play.

I've made changes regarding the limitation. Now I'm doing a refactoring because lots of beacons don't fit to main screen at the moment. It's little bit complex for me. I'll close this issue on github after I solve it. I think I can finish during this week. Stay tuned.

**Comment by turbulator** [comment]
Done in 0.3 build 10
