### ISSUE TITLE
APK package?

### ISSUE THREAD

**Issue by eisengrau** [turbo-lab/android-beacon-mqtt#39]
Hello,

Is there any chance that you can provide an APK build of the app? You know, for us, de-googled folks :).

Thank You!

**Comment by royrogermcfreely** [comment]
hey,

there is a apk in the release section:
Direct link: [APK File](https://github.com/turbo-lab/android-beacon-mqtt/releases/download/v0.2.1/beacon-mqtt-0.2.1.apk)
Release Link; [Link](https://github.com/turbo-lab/android-beacon-mqtt/releases)

/roy

**Comment by turbulator** [comment]
Hi folks!

Since Google had changed their rules about location permissions I lost a possibility to publish my app to google play.
So, I opened the source code of the app. You can clone and build it yourself if you are interested in.

This repository contains last, acual sources and very early binaries. Unfortunetely I heven't done Travis CI setup yet. But I'll push last APK today.

**Comment by turbulator** [comment]
Published
